server:
  port: 8080   # Gateway will run on 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true          # Allow dynamic routes by serviceId
          lower-case-service-id: true
      routes:
        # Route to flight-service
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/api/flights/**

        # Route to booking-service
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
            # later booking controller paths will start with /api/bookings/...

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
