server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # =================== FLIGHT-SERVICE ===================
        - id: flight-service
          uri: lb://FLIGHT-SERVICE
          predicates:
            # external paths exposed by gateway
            - Path=/api/flights/**,/api/flights/search/**,/api/flights/*
          filters:
            # /api is removed before forwarding -> flight-service sees /flights/...
            - StripPrefix=1

        # =================== BOOKING-SERVICE ==================
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          # Same secret you use when generating JWT on jwt.io
          secret-key: "my-super-secret-jwt-key-that-is-long-enough"

eureka:
  client:
    service-url:
      # Eureka container name
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,gateway
