server:
  port: 8091   # 8090 already used by flight-service

spring:
  application:
    name: booking-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/bookingdbnew   # second Mongo DB for bookings

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
