server:
  port: 8091

spring:
  application:
    name: booking-service

  rabbitmq:
    host: rabbitmq-broker
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      # Mongo container name from docker-compose
      uri: mongodb://mongodb:27017/flights_micro_db

eureka:
  client:
    service-url:
      # Eureka container name from docker-compose
      defaultZone: http://eureka-server:8761/eureka
