server:
  port: 8091

spring:
  application:
    name: booking-service
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      uri: mongodb://localhost:27017/flights_micro_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
