spring:
  application:
    name: booking-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/booking_micro_db

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8091

booking:
  exchange: booking.exchange
  routingKey: booking.key
  queue: booking.queue
