server:
  port: 0

spring:
  application:
    name: booking-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookingdb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      flightService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

app:
  booking:
    queue: booking-queue
