server:
  port: 8090   

spring:
  application:
    name: flight-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/flightdbnew

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: INFO
    org.springframework.web: INFO
