server:
  port: 0   # random free port

spring:
  application:
    name: flight-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/flightdbnew

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
