server:
  port: 8090

spring:
  application:
    name: flight-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: flights_micro_db    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
